### ISSUE TITLE
Human Motion Modelling Demo

### ISSUE THREAD

**Issue by johannakarras** [azuxmioy/Render-In-Between#1]
It seems like the example on the home page for Human Motion Modelling will throw an error if you do not download the Amass_3D_joints.h5 file. I found a way to work around it and run the demo simply by commenting out lines 65-70 inside of AMASS_dataset.py.

**Comment by azuxmioy** [comment]
Thank you for your interest. You are right, the dataset should be optional during inference. I have made a small change.
