### ISSUE TITLE
About the input of conditonal image for Foreground Human Image Generation

### ISSUE THREAD

**Issue by Gancheekim** [azuxmioy/Render-In-Between#3]
Hi, in the original paper, section 3.3's Foreground Human Image Generation, it stated that:
`
"In our case, the conditional image represents the 2D joints pt and connecting limbs"
`,
can you tell me which part of the code implements this? In my understanding, the 2D joints might be something like tensor of shape [2,19], and the conditional image might be something like tensor of shape [B,C,H,W]?

**Comment by azuxmioy** [comment]
Hi, thanks for reaching out.

If my memory is correct they are all like image shapes. (Sorry that this project is old and outdated)

maybe this line is what you need
https://github.com/azuxmioy/Render-In-Between/blob/main/Pose_Guided_Neural_Rendering/models/trainer.py#L152

**Comment by Gancheekim** [comment]
@azuxmioy Thank you for replying, the project is very interesting.

For anyone wondering about the conditional image, the 2D joints is transformed into a [19, H, W] heatmap, and the limbs are formed by connecting them into a [3, H, W] map.
https://github.com/azuxmioy/Render-In-Between/blob/94bc1a6007d436d8ce541020a6c8fc7b5ff8a9c5/Pose_Guided_Neural_Rendering/datasets/HSM_auto_dataset.py#L205
https://github.com/azuxmioy/Render-In-Between/blob/94bc1a6007d436d8ce541020a6c8fc7b5ff8a9c5/Pose_Guided_Neural_Rendering/datasets/HSM_auto_dataset.py#L238
